/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FollowUserResponse {
  'principal' : Principal,
  'username' : string,
  'displayName' : string,
  'profilePictureHash' : [] | [ExternalBlob],
}
export interface Notification {
  'id' : bigint,
  'notificationType' : NotificationType,
  'createdAt' : Time,
  'isRead' : boolean,
  'actorUsername' : string,
  'actorPrincipal' : Principal,
}
export type NotificationType = { 'repost' : bigint } |
  { 'like' : bigint } |
  { 'quote' : bigint } |
  { 'mention' : bigint } |
  { 'reply' : bigint } |
  { 'follow' : null };
export interface PaginatedFollows {
  'nextOffset' : [] | [bigint],
  'hasMore' : boolean,
  'users' : Array<FollowUserResponse>,
}
export interface PaginatedNotifications {
  'hasMore' : boolean,
  'notifications' : Array<Notification>,
  'nextCursor' : [] | [bigint],
}
export interface PaginatedPosts {
  'hasMore' : boolean,
  'posts' : Array<PostResponse>,
  'nextCursor' : [] | [bigint],
}
export interface PostResponse {
  'id' : bigint,
  'postType' : PostType,
  'authorUsername' : string,
  'likeCount' : bigint,
  'isRepostedByCurrentUser' : boolean,
  'authorProfilePictureHash' : [] | [ExternalBlob],
  'repostCount' : bigint,
  'createdAt' : Time,
  'text' : string,
  'author' : Principal,
  'mediaHash' : [] | [ExternalBlob],
  'replyCount' : bigint,
  'mediaType' : [] | [string],
  'editedAt' : [] | [Time],
  'authorDisplayName' : string,
  'isLikedByCurrentUser' : boolean,
}
export type PostType = { 'repost' : bigint } |
  { 'quote' : bigint } |
  { 'original' : null } |
  { 'reply' : bigint };
export type Time = bigint;
export interface TrendingHashtag { 'tag' : string, 'count' : bigint }
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'headerImageHash' : [] | [ExternalBlob],
  'profilePictureHash' : [] | [ExternalBlob],
}
export interface UserProfileResponse {
  'bio' : string,
  'isBlockedByCurrentUser' : boolean,
  'principal' : Principal,
  'username' : string,
  'displayName' : string,
  'isMutedByCurrentUser' : boolean,
  'followersCount' : bigint,
  'createdAt' : Time,
  'updatedAt' : Time,
  'headerImageHash' : [] | [ExternalBlob],
  'followingCount' : bigint,
  'isFollowedByCurrentUser' : boolean,
  'profilePictureHash' : [] | [ExternalBlob],
  'postsCount' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'checkUsernameAvailability' : ActorMethod<[string], boolean>,
  'createPost' : ActorMethod<
    [string, [] | [ExternalBlob], [] | [string]],
    PostResponse
  >,
  'createReply' : ActorMethod<
    [bigint, string, [] | [ExternalBlob], [] | [string]],
    PostResponse
  >,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'editPost' : ActorMethod<[bigint, string], PostResponse>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getFollowers' : ActorMethod<[string, bigint, bigint], PaginatedFollows>,
  'getFollowing' : ActorMethod<[string, bigint, bigint], PaginatedFollows>,
  'getGlobalFeed' : ActorMethod<[[] | [bigint], bigint], PaginatedPosts>,
  'getHomeFeed' : ActorMethod<[[] | [bigint], bigint], PaginatedPosts>,
  'getNotifications' : ActorMethod<
    [[] | [bigint], bigint],
    PaginatedNotifications
  >,
  'getPost' : ActorMethod<[bigint], [] | [PostResponse]>,
  'getPostsByHashtag' : ActorMethod<
    [string, [] | [bigint], bigint],
    PaginatedPosts
  >,
  'getPostsByUser' : ActorMethod<
    [Principal, [] | [bigint], bigint],
    PaginatedPosts
  >,
  'getPostsByUsername' : ActorMethod<
    [string, [] | [bigint], bigint],
    PaginatedPosts
  >,
  'getPrincipalByUsername' : ActorMethod<[string], [] | [Principal]>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getProfileByUsername' : ActorMethod<[string], [] | [UserProfileResponse]>,
  'getReplies' : ActorMethod<[bigint, [] | [bigint], bigint], PaginatedPosts>,
  'getTrendingHashtags' : ActorMethod<[bigint], Array<TrendingHashtag>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileResponse]>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'muteUser' : ActorMethod<[Principal], undefined>,
  'quotePost' : ActorMethod<
    [bigint, string, [] | [ExternalBlob], [] | [string]],
    PostResponse
  >,
  'repostPost' : ActorMethod<[bigint], PostResponse>,
  'searchPosts' : ActorMethod<[string, [] | [bigint], bigint], PaginatedPosts>,
  'searchUsers' : ActorMethod<[string, bigint], Array<UserProfileResponse>>,
  'setProfile' : ActorMethod<[string, string, string], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'undoRepost' : ActorMethod<[bigint], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'unmuteUser' : ActorMethod<[Principal], undefined>,
  'updateHeaderImage' : ActorMethod<[[] | [ExternalBlob]], undefined>,
  'updateProfilePicture' : ActorMethod<[[] | [ExternalBlob]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];